### ISSUE TITLE
[SUGGESTIONS] Settings file improvements

### ISSUE THREAD

**Issue by ivanrj7j** [g-sree-jith/Indeed-Scraper#5]
It is really difficult to deal with the settings.py file

modify the settings.py file so that

- Include only the necessary parts
- Instead of commenting out the unused code, make a `settings.md` file and have a detailed summary on how to use settings. You can use something like `ChatGPT` or `Claude AI` to do the task.

**Comment by g-sree-jith** [comment]
settings.md file created with necessary updates
